### PR TITLE
Drop Node 10, etc.

### PR DESCRIPTION
**Pull request by Nargonath**
This is a breaking change too.

### CODE REVIEW

**Comment by Nargonath** [comment]
this is linked to #92

**Comment by Nargonath** [comment]
@devinivy  `knex@21` drop support for Node 8. Do we want to bump the peerDep to `v21` as well?

**Comment by Nargonath** [comment]
Also now the PR fixes #92

**Comment by devinivy** [comment]
Thanks @Nargonath!  I think we'll leave the knex peer dep at v0.16 for now, since that version did eventually support node v12 (and there's no feature in future versions that I anticipate schwifty needing).

**Comment by Nargonath** [comment]
You're welcome @devinivy. If we keep knex as is there shouldn't be any more work required on this PR otherwise please let me know and I'll do whatever is required. 👍

**Comment by devinivy** [comment]
This looks good— going to roll it into the new v6 branch and keep working from here.  Thanks again 👍

**Comment by Nargonath** [comment]
You're welcome. 😉

**Pull request merged**
