### PR TITLE
Set joi as dep and @hapi/joi as devDep

### LINKED ISSUE #13: Tests do not run due to missing nested dependency
I tried to run the test locally but I get this error when I do:

```
> hpal-debug@1.5.0 test /home/jpauthier/workspace/hpal-debug
> lab -a @hapi/code -t 100 -L -I "FinalizationRegistry,WeakRef"

Error requiring file: /home/jpauthier/workspace/hpal-debug/test/closet/repl/pal-plugins/server.js
Cannot find module 'joi'
Require stack:
- /home/jpauthier/workspace/hpal-debug/node_modules/schwifty/lib/index.js
- /home/jpauthier/workspace/hpal-debug/test/closet/repl/pal-plugins/server.js
- /home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/lib/cli.js
- /home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/bin/lab
Error: Cannot find module 'joi'
Require stack:
- /home/jpauthier/workspace/hpal-debug/node_modules/schwifty/lib/index.js
- /home/jpauthier/workspace/hpal-debug/test/closet/repl/pal-plugins/server.js
- /home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/lib/cli.js
- /home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/bin/lab
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/jpauthier/workspace/hpal-debug/node_modules/schwifty/lib/index.js:6:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.require.extensions.<computed> [as .js] (/home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/lib/coverage.js:127:28)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/jpauthier/workspace/hpal-debug/test/closet/repl/pal-plugins/server.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.require.extensions.<computed> [as .js] (/home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/lib/coverage.js:127:28)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/lib/cli.js:134:13
    at Array.forEach (<anonymous>)
    at Object.internals.traverse (/home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/lib/cli.js:128:15)
    at Object.exports.run (/home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/lib/cli.js:61:31)
    at main (/home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/bin/lab:56:48)
    at Object.<anonymous> (/home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/bin/lab:60:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! Test failed.  See above for more details.
```

The problem seems to be coming from Schwifty. In the `lib/index.js` we `require('joi')` but `joi` is a `devDependency` and `@hapi/joi@16` is in the `dependencies` section. That way I guess it works when running Schwifty from the repo itself. I believe devDeps are not installed when installing a package dependency from NPM and as hpal-debug does not have joi in its dependencies but rather `joi-17` joi is nowhere to be found in the dependency tree thus it breaks when running `hpal-debug` tests.

### PR DESCRIPTION
**Pull request by Nargonath**
Fixes https://github.com/hapipal/hpal-debug/issues/13.

Schwifty still has a peerDep on `@hapi/joi` but I wasn't sure if I should remove it or not since I believe schwifty receives Joi object from the user.

### CODE REVIEW

**Comment by devinivy** [comment]
Oh my!  Good call.  This is a bug, but I think the issue is with the code rather than the deps.  I can't move directly to use `joi` as a dependency because it technically doesn't support the same range of nodejs versions as schwifty (though fun fact: the joi v17 test suite does pass on node v8!).  Joi is a peer to schwifty only because it has to inspect and create modifications to the schema that users place on their models, not for internal validation.  Thanks for looking into this!

**Comment by Nargonath** [comment]
Alright, thanks for the explanation. Isn't it also the point to make schwifty requires node >= 12 hence we'll switch back to Joi? Perhaps you wanted to separate the bug fix from the breaking change to publish it sooner, didn't you?

**Comment by devinivy** [comment]
Yeah, exactly.  That was a fairly bad bug.  I also want to leave these pre-nodev12+ versions of all the modules in good condition before the next versions go out.  In the next version of schwifty we will use `joi` internally rather than `@hapi/joi` 👍

**Comment by Nargonath** [comment]
Good call indeed. Thanks for the details. 😉

**Pull request closed without merging**
