### PR TITLE
Upgrading dependencies

### PR DESCRIPTION
**Pull request by tmbarkve**
Upgrading dependencies:

* Joi -> v.16
* Code -> v.6
* Lab -> v.20
* Hoek -> v.8

Fixing breaking changes caused by Joi 16.

### CODE REVIEW

**Comment by devinivy** [comment]
Thank you for this!  I'm realizing that it's a breaking change to schwifty, so I'm trying to decide whether to release it as a new major version or to introduce a compatibility layer for joi v16.  Any opinions out there?

**Comment by YoannMa** [comment]
I think it's easier to release a new major than introducing a compability layer, right ?

**Comment by YoannMa** [comment]
@devinivy thinking it could be better to wait for Objection v2 as it's in alpha currently ?

**Comment by tmbarkve** [comment]
Actually, I'm having some issues with the fork(), when passing joi-types `optional()` set. I'll try to make a reproduction, so the migration is perhaps more complex than I first anticipated.

**Comment by devinivy** [comment]
No rush here, but I wanted to check-in.  Do you think this is a joi issue, or more of a usage issue?

**Comment by devinivy** [comment]
@tmbarkve I gave this some review today, and I didn't find anything weird other than the fact that we're still using `options()` rather than the canonical `prefs()`.  But they are aliases of each other for now, so it shouldn't be causing issues.  Do you have any further insights into what issues you experienced?  I am happy to look into them myself if I have a slightly closer place to start.

**Comment by tmbarkve** [comment]
Hi @devinivy, we experienced some issues, but I never got to finish the project before changing job. My findings were pretty much that this worked fine with all the unit tests and so on, but I had some hickups in my system. Don't think this should be of any concern in regards to schwifty. Sorry for the inactivity...

**Pull request merged**
